### ISSUE TITLE
Streaming read?

### ISSUE THREAD

**Issue by markg85** [omarabid/ipfs-cid#2]
Hi,

Nifty little tool you made there! Nice!

I'm curious if you would be able to change the file reading to be able to handle large files?
Like files larger then the system memory ;)

Here's a nice rust comparison of large file reading methods that i stumbled upon, you might find them interesting.
https://sensepost.com/blog/2023/reading-large-files-and-perf/

It's probably a bit more involved then just reading the file differently. It looks like your `generate_cid` function might need some changes for this too?

Cheers,
Mark

**Comment by omarabid** [comment]
@markg85 You'll need to understand how the hashing function works and if you can determine the final hash from a stream of bytes. Feel free to open a PR for it if it is something you are working on.
